### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CMS-Internetsolutions** [CPS-IT/typo3-project-template#88]
### PHP version

8.2.10

### Composer version

2.5.8

### Package version

9.2

### Project Builder version

last

### Operating system

Ubuntu 23.10

### Current behavior

See Attached Error
![Bildschirmfoto vom 2024-03-25 16-56-28](https://github.com/CPS-IT/typo3-project-template/assets/107540699/068d7dee-af53-4ca2-95ca-444d87818f17)

**Comment by mteu** [comment]
Hey @CMS-Internetsolutions, it looks like a connectivity issue on your site. I could reach packagist just fine, today. Are you able to fetch everything now?

**Comment by CMS-Internetsolutions** [comment]
thx for the fast answer ... i will try it again!!!
